name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dockerize:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Build the Image
    - uses: actions/checkout@v2
    - run: docker build . --file Dockerfile --tag rrkelley/bulletinboard-rrk:latest
